batchsize: 64
iteration: 100000
iteration_decay_start: 50000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 500
evaluation_interval: 500

models:
  generator:
    fn: gen_models/resnet_64.py
    name: ResNetGenerator
    args:
      dim_z: 128
      bottom_width: 4
      ch: 64
      n_classes: 0

  discriminator:
      fn: dis_models/snresnet_64.py
      name: SNResNetProjectionDiscriminator
      args:
        ch: 64
        n_classes: 0

dataset:
  dataset_fn: datasets/video10000.py
  dataset_name: Video10000Dataset
  args:
    path: datasets/image_list_video10k.txt
    size: 64

adam:
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

updater:
  fn: updater.py
  name: Updater
  args:
    n_dis: 5
    n_gen_samples: 64
    conditional: False
    loss_type: hinge